name: "🚀 Feature Request"
description: Submit a proposal/request for a new Langflow feature
labels: [ "enhancement" ]
body:
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature Request
      description: |
        A clear and concise description of the feature proposal. Please provide any relevant links to papers, code, or other resources that support your proposal.

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: |
        Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link it here as well.

  - type: textarea
    id: contribution
    attributes:
      label: Your Contribution
      description: |
        Is there any way that you could help, e.g., by submitting a PR? Make sure to read the CONTRIBUTING.md guidelines for Langflow before proceeding.
