name: autofix.ci
on:
  pull_request:
    paths:
      - "**/*.py"
env:
  POETRY_VERSION: "1.8.2"

jobs:
  lint:
    name: Run Ruff Check and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Environment"
        uses: ./.github/actions/setup-uv
      - run: uv run ruff check --fix-only .
      - run: uv run ruff format .
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
      - name: Minimize uv cache
        run: uv cache prune --ci
